[package]
name = "serde_bibtex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7"
itertools = "0.12"
serde = { version = "1.0", features = ["derive"] }
unicase = "2.7"
memchr = "2.7"

[dev-dependencies]
trace = "0.1"
proptest = "1.0.0"
